
#ifndef SOFTSPI_CONFIGURATION_H_
#define SOFTSPI_CONFIGURATION_H_

#define SOFTSPI_MISO_DDR   DDRB
#define SOFTSPI_MISO_PINX  PINB
#define SOFTSPI_MISO_PIN   0

#define SOFTSPI_MOSI_DDR   DDRC
#define SOFTSPI_MOSI_PORT  PORTC
#define SOFTSPI_MOSI_PIN   5

#define SOFTSPI_CLK_DDR    DDRD
#define SOFTSPI_CLK_PORT   PORTD
#define SOFTSPI_CLK_PIN    7

#define SOFTSPI_MODE       SOFTSPI_MODE_0
#define SOFTSPI_DATA_ORDER SOFTSPI_DATA_IS_ORDER_HIGHEST_BIT

#endif
